### ISSUE TITLE
Catástrofe: día 23 de mayo del 2022

### ISSUE THREAD

**Issue by nepito** [IslasGECI/development_server_setup#6]
No funcionó generar el servidor a partir de terraform. No pudimos identificarnos a partir de las llaves ssh.

Aquí podemos ver los errores:
![image](https://user-images.githubusercontent.com/35377740/169882660-ceb0a666-796b-471e-8c39-db90d13b1588.png)

**Comment by nepito** [comment]
220526: Hicimos el servidor a pie, desde el DO y la configuración desde el contenedor.

**Comment by mvillasante** [comment]
Supongo que con esto podemos descansar tranquilos y cerrar este issue.
https://islas.slack.com/archives/GC240U1MF/p1653440756293939
