### ISSUE TITLE
Los cambios en los _scripts_ no se ven reflejados si montamos un volumen en `src/`

### ISSUE THREAD

**Issue by devarops** [IslasGECI/development_server_setup#9]
Los archivos que resultan de `terraform init` se guardan en el directorio `src/`.
Para ejecutar `make destroy_server` montamos un volumen en `src/` para que los archivos de terraform persistan.
Cuando los _scripts_ en `src/` cambian, los cambios no se ven reflejados cuando montamos el volumen en `src/`.
Esperaríamos que la persistencia de los archivos de Terraform no impida ver la versión más reciente de los _scripts_.

**Comment by nepito** [comment]
¿Qué es lo que esperamos que suceda?

**Comment by devarops** [comment]
Esperaríamos la persistencia de los archivos de terraform no impida ver la versión más reciente de los _scripts_.

Una manera de resolverlo es que los _scripts_ y los archivos que resultan del terraform se encuentren en directorios distintos.
